#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_flannel="$(flanneld --version 2>&1 | perl -pe 's{^v}{}' || true)"
  jq -n --arg flannel "$ver_flannel" '{flannel: $flannel}'
}

version "$@"
